const productos = [
    {   id: 1,
        titulo: 'Nike Metcon 8 FlyEase',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 104,
        categoria: 'zapatilla',
        tag: "deportiva",
        url: 'https://i.ibb.co/6Y0Zbf5/zd1.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 2,
        titulo: 'Nike SuperRep Go 3 Flyknit',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 109,
        categoria: 'zapatilla',
        tag: "deportiva",
        url: 'https://i.ibb.co/9Zt3VLq/zd2.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 3,
        titulo: 'Adidas Galaxy 6 R',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 42,
        categoria: 'zapatilla',
        tag: "deportiva",
        url: 'https://i.ibb.co/x8D4V8h/zd3.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 4,
        titulo: 'Adidas 4DFWD X PARLEY',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 110,
        categoria: 'zapatilla',
        tag: "deportiva",
        url: 'https://i.ibb.co/0ZNqG0J/zd4.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 5,
        titulo: 'Puma Voyage Nitro',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 99,
        categoria: 'zapatilla',
        tag: "deportiva",
        url: 'https://i.ibb.co/M9T16xS/zd5.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 6,
        titulo: 'Puma Softride Enzo NXT',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 48,
        categoria: 'zapatilla',
        tag: "urbana",
        url: 'https://i.ibb.co/hcxgf8N/zu1.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 7,
        titulo: 'Puma X-Ray 2 Square',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 55,
        categoria: 'zapatilla',
        tag: "urbana",
        url: 'https://i.ibb.co/MVtDxQ6/zu2.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 8,
        titulo: 'Adidas NMD',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 75,
        categoria: 'zapatilla',
        tag: "urbana",
        url: 'https://i.ibb.co/jVyhFw7/zu3.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 9,
        titulo: 'Adidas NMD_R1 V3',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 128,
        categoria: 'zapatilla',
        tag: "urbana",
        url: 'https://i.ibb.co/85Zp30h/zu4.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 10,
        titulo: 'Nike Air Max Plus III',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 180,
        categoria: 'zapatilla',
        tag: "urbana",
        url: 'https://i.ibb.co/HNkzgh3/zu5.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 11,
        titulo: 'Nike Air Huarache',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 78,
        categoria: 'zapatilla',
        tag: "urbana",
        url: 'https://i.ibb.co/VMNxJ95/zu6.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 12,
        titulo: 'Fila Hallasan Mid Premium',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 138,
        categoria: 'zapatilla',
        tag: "urbana",
        url: 'https://i.ibb.co/XWHvshF/zu7.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 13,
        titulo: 'Nike CloudFoam Pure 2.0',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 56,
        categoria: 'zapatilla',
        tag: "urbana",
        url: 'https://i.ibb.co/Ln6FRTP/zu8.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 14,
        titulo: 'Nike Air Zoom Fir',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 130,
        categoria: 'zapatilla',
        tag: "urbana",
        url: 'https://i.ibb.co/0hPTX44/zu9.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 15,
        titulo: 'Adidas Hoodie Logo',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 70,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/545pWTJ/ho1.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 16,
        titulo: 'Adidas Hoodie Essentials FullZip',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 45,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/sgtWM8w/ho2.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 17,
        titulo: 'Adidas Hoodie Adicolor Cropped',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 45,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/WKNxQR0/ho3.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 18,
        titulo: 'Adidas Hoodie Adicolor Neuclassics',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 70,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/v4YVG6S/ho4.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 19,
        titulo: 'UnderArmour Fleece',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 60,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/thq8ND9/ho5.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 20,
        titulo: 'UnderArmour Rival Fleece Wordmark',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 55,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/9rf35SP/ho6.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 21,
        titulo: 'UnderArmour Fleece  Big Logo',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 60,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/dJfHgjd/ho7.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 22,
        titulo: 'UnderArmour Journey Fleece FullZip',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 90,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/McVyRDC/ho8.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 23,
        titulo: 'Puma Essentials +',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 50,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/N6Jw00Q/ho9.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 24,
        titulo: 'Puma Run Cloudspun',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 70,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/q7Q8Bwj/ho10.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 25,
        titulo: 'Puma PowerCat',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 65,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/X5xbMKH/ho11.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 26,
        titulo: 'Supreme Blueberry',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 429,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/0jbsJsd/ho12.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 27,
        titulo: 'Supreme Swarovski',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 849,
        categoria: 'indumentaria',
        tag: "hoodie",
        url: 'https://i.ibb.co/NYNCd6J/ho13.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 28,
        titulo: 'Adidas Adicolor Classics 3-Stripes',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 30,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/synVFV3/rm1.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 29,
        titulo: 'Adidas Adicolor Classics Curvy',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 33,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/G3FQHwZ/rm2.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 30,
        titulo: 'Fila Jersey Goalie',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 88,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/SxjjS6k/rm3.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 31,
        titulo: 'Fila Witely Top',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 48,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/XZVxv3y/rm4.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 32,
        titulo: 'Versace Medusa Cristalli',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 890,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/MRYQsLR/rm5.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 33,
        titulo: 'Adidas Train Icons 3-Stripes',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 45,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/LkX6FyG/rh1.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 34,
        titulo: 'Adidas Adicolor Seasonal Arcive',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 35,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/GVD13yG/rh2.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 35,
        titulo: 'Adidas Icone Berlin City',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 33,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/LzyBy7X/rh3.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 36,
        titulo: 'Adidas Adicolor Neuclassics',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 45,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/4YrPgj4/rh4.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 37,
        titulo: 'Adidas Rekive',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 35,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/8bPPrGB/rh5.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 38,
        titulo: 'Adidas Hiit',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 38,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/C2nCrLs/rh6.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 39,
        titulo: 'Puma Essentials+ Logo Lab',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 25,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/H2mRphB/rh7.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 40,
        titulo: 'Fila Jersey 2Pac Baseball',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 75,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/MVM6zz3/rh8.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 41,
        titulo: 'Nike Chicago Bulls Courtside',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 39,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/x6GTc0F/rh9.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 42,
        titulo: 'Puma Power Colourblock',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 30,
        categoria: 'indumentaria',
        tag: "remera",
        url: 'https://i.ibb.co/grjcCsq/rh10.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 43,
        titulo: 'Casio WS-1500H-1AV',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 39,
        categoria: 'reloj',
        tag: "analogico",
        url: 'https://i.ibb.co/pQnhD0k/reh1.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 44,
        titulo: 'Casio GMA-S2100BA-3A',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 99,
        categoria: 'reloj',
        tag: "analogico",
        url: 'https://i.ibb.co/7424Lyp/reh2.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 45,
        titulo: 'Casio MRG-B2000GA-1A',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 550,
        categoria: 'reloj',
        tag: "analogico",
        url: 'https://i.ibb.co/5vrqf1Q/reh3.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 46,
        titulo: 'Casio GMA-S2100BA-2A2',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 99,
        categoria: 'reloj',
        tag: "analogico",
        url: 'https://i.ibb.co/6HY3QhB/rem1.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 47,
        titulo: 'Casio LTP-1302PRG-7AV',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 79,
        categoria: 'reloj',
        tag: "analogico",
        url: 'https://i.ibb.co/tDCxmZS/rem2.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 48,
        titulo: 'Apple Watch Series 8',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 509,
        categoria: 'reloj',
        tag: "smart",
        url: 'https://i.ibb.co/WzkbVB6/rs1.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 49,
        titulo: 'Apple Watch SE',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 309,
        categoria: 'reloj',
        tag: "smart",
        url: 'https://i.ibb.co/gZLV6Qy/rs2.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 50,
        titulo: 'Samsung Galaxy Watch 5',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 329,
        categoria: 'reloj',
        tag: "smart",
        url: 'https://i.ibb.co/mzGL1Tz/rs3.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 51,
        titulo: 'Xiaomi Watch S1 Active',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 169,
        categoria: 'reloj',
        tag: "smart",
        url: 'https://i.ibb.co/wpmGk1V/rs4.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 52,
        titulo: 'Sony WH-1000XM4',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 380,
        categoria: 'electronica',
        tag: "auriculares",
        url: 'https://i.ibb.co/1K6z0tc/a1.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 53,
        titulo: 'SkullCandy Crusher Evo Sensory Bass',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 199,
        categoria: 'electronica',
        tag: "auriculares",
        url: 'https://i.ibb.co/7GYTYgF/a2.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 54,
        titulo: 'JBL Une 760NC',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 99,
        categoria: 'electronica',
        tag: "auriculares",
        url: 'https://i.ibb.co/YQZ0Jt0/a3.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 55,
        titulo: 'Sennheiser Hd 350BT',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 66,
        categoria: 'electronica',
        tag: "auriculares",
        url: 'https://i.ibb.co/pWdrv2V/a4.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 56,
        titulo: 'Sony WF-1000XM3',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 250,
        categoria: 'electronica',
        tag: "earbuds",
        url: 'https://i.ibb.co/7pTNCbw/a10.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 57,
        titulo: 'JBL Tune Flex',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 85,
        categoria: 'electronica',
        tag: "earbuds",
        url: 'https://i.ibb.co/V2PSGhK/a11.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 58,
        titulo: 'Apple AirPods Pro (2nd generation)',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 249,
        categoria: 'electronica',
        tag: "earbuds",
        url: 'https://i.ibb.co/TLT1pfC/a12.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 59,
        titulo: 'Apple Buy HomePod Mini',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 99,
        categoria: 'electronica',
        tag: "speakers",
        url: 'https://i.ibb.co/CttxSVF/s1.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 60,
        titulo: 'JBL Charge 5',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 199,
        categoria: 'electronica',
        tag: "speakers",
        url: 'https://i.ibb.co/hHhjF9S/s2.png',
        new: false,
        sale: false,
        sold: false
    },
    {   id: 61,
        titulo: 'Sony XG500 Serie X',
        descripcion : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        precio: 450,
        categoria: 'electronica',
        tag: "speakers",
        url: 'https://i.ibb.co/Fq96Dsy/s3.png',
        new: false,
        sale: false,
        sold: false
    },
]
